"""Add _en fields

Revision ID: 931c03a8f114
Revises: 5862b8ff2955
Create Date: 2026-03-13 02:10:20.670400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '931c03a8f114'
down_revision = '5862b8ff2955'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('categories') as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_categories_name_en', ['name_en'])
    with op.batch_alter_table('products') as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('category_en', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_category_en'), ['category_en'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name_en'), ['name_en'], unique=False)
    with op.batch_alter_table('stores') as batch_op:
        batch_op.add_column(sa.Column('theme_color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('background_image_url', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('store_ads', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('announcement_text', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('currency_display', sa.String(length=10), nullable=True))
        batch_op.drop_column('return_policy')
        batch_op.drop_column('shipping_policy')
    with op.batch_alter_table('suppliers') as batch_op:
        batch_op.add_column(sa.Column('override_limits', sa.JSON(), nullable=True))
    with op.batch_alter_table('vendor_plans') as batch_op:
        batch_op.add_column(sa.Column('max_coupons', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allow_whatsapp_checkout', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_plans', 'allow_whatsapp_checkout')
    op.drop_column('vendor_plans', 'max_coupons')
    op.drop_column('suppliers', 'override_limits')
    op.add_column('stores', sa.Column('shipping_policy', sa.TEXT(), nullable=True))
    op.add_column('stores', sa.Column('return_policy', sa.TEXT(), nullable=True))
    op.drop_column('stores', 'currency_display')
    op.drop_column('stores', 'announcement_text')
    op.drop_column('stores', 'store_ads')
    op.drop_column('stores', 'background_image_url')
    op.drop_column('stores', 'theme_color')
    op.drop_index(op.f('ix_products_name_en'), table_name='products')
    op.drop_index(op.f('ix_products_category_en'), table_name='products')
    op.drop_column('products', 'category_en')
    op.drop_column('products', 'description_en')
    op.drop_column('products', 'name_en')
    with op.batch_alter_table('categories') as batch_op:
        batch_op.drop_constraint('uq_categories_name_en', type_='unique')
        batch_op.drop_column('description_en')
        batch_op.drop_column('name_en')
    op.create_table('markup_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('is_global', sa.BOOLEAN(), nullable=False),
    sa.Column('markup_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('markup_value', sa.FLOAT(), nullable=False),
    sa.Column('min_price', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_markup_rules_supplier_id', 'markup_rules', ['supplier_id'], unique=False)
    op.create_index('ix_markup_rules_product_id', 'markup_rules', ['product_id'], unique=False)
    op.create_index('ix_markup_rules_id', 'markup_rules', ['id'], unique=False)
    op.create_index('ix_markup_rules_category_id', 'markup_rules', ['category_id'], unique=False)
    op.create_table('advertisements',
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('target_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('placement', sa.VARCHAR(length=50), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('cost', sa.FLOAT(), nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_advertisements_id', 'advertisements', ['id'], unique=False)
    op.create_table('admin_settings',
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_settings_key', 'admin_settings', ['key'], unique=False)
    op.create_index('ix_admin_settings_id', 'admin_settings', ['id'], unique=False)
    op.create_table('ui_widgets',
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('settings_json', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_ui_widgets_id', 'ui_widgets', ['id'], unique=False)
    # ### end Alembic commands ###
