"""Initial schema

Revision ID: 2dcc6fba20f1
Revises: 
Create Date: 2026-03-19 02:18:30.678574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2dcc6fba20f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vendor_followers_id', table_name='vendor_followers')
    op.drop_index('ix_vendor_followers_supplier_id', table_name='vendor_followers')
    op.drop_index('ix_vendor_followers_user_id', table_name='vendor_followers')
    op.drop_table('vendor_followers')
    op.drop_table('sqlite_sequence')
    op.drop_index('ix_cms_theme_settings_id', table_name='cms_theme_settings')
    op.drop_table('cms_theme_settings')
    op.drop_index('ix_cms_widgets_legacy_id', table_name='cms_widgets_legacy')
    op.drop_table('cms_widgets_legacy')
    op.drop_index('ix_admin_settings_id', table_name='admin_settings')
    op.drop_index('ix_admin_settings_key', table_name='admin_settings')
    op.drop_table('admin_settings')
    op.drop_index('ix_markup_rules_category_id', table_name='markup_rules')
    op.drop_index('ix_markup_rules_id', table_name='markup_rules')
    op.drop_index('ix_markup_rules_product_id', table_name='markup_rules')
    op.drop_index('ix_markup_rules_supplier_id', table_name='markup_rules')
    op.drop_table('markup_rules')
    op.drop_index('ix_ui_widgets_id', table_name='ui_widgets')
    op.drop_table('ui_widgets')
    op.drop_index('ix_cms_ads_id', table_name='cms_ads')
    op.drop_table('cms_ads')
    op.drop_table('advertisements')
    op.add_column('categories', sa.Column('name_en', sa.String(length=128), nullable=True))
    op.add_column('categories', sa.Column('description_en', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'categories', ['name_en'])
    op.alter_column('cms_pages', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_index('ix_cms_pages_slug', table_name='cms_pages')
    op.create_index(op.f('ix_cms_pages_slug'), 'cms_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_cms_pages_id'), 'cms_pages', ['id'], unique=False)
    op.alter_column('cms_widgets', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_cms_widgets_id'), 'cms_widgets', ['id'], unique=False)
    op.add_column('fulfillment_orders', sa.Column('total_vendor_share', sa.Float(), nullable=True))
    op.add_column('fulfillment_orders', sa.Column('total_shipping_cost', sa.Float(), nullable=True))
    op.add_column('fulfillment_orders', sa.Column('total_affiliate_commission', sa.Float(), nullable=True))
    op.add_column('order_items', sa.Column('affiliate_commission', sa.Float(), nullable=True))
    op.add_column('orders', sa.Column('shipping_cost', sa.Float(), nullable=False))
    op.add_column('orders', sa.Column('affiliate_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('affiliate_commission', sa.Float(), nullable=True))
    op.create_index(op.f('ix_orders_affiliate_id'), 'orders', ['affiliate_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'affiliates', ['affiliate_id'], ['id'])
    op.create_index(op.f('ix_product_variation_variable_values_identifier'), 'product_variation_variable_values', ['identifier'], unique=False)
    op.add_column('products', sa.Column('name_en', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('description_en', sa.String(length=1024), nullable=True))
    op.add_column('products', sa.Column('category_en', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_products_category_en'), 'products', ['category_en'], unique=False)
    op.create_index(op.f('ix_products_name_en'), 'products', ['name_en'], unique=False)
    op.drop_column('stores', 'shipping_policy')
    op.drop_column('stores', 'return_policy')
    op.add_column('suppliers', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('suppliers', sa.Column('logo_url', sa.String(length=512), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'products', ['pinned_product_id'], ['id'])
    op.drop_column('suppliers', 'subscription_plan_id')
    op.drop_column('suppliers', 'billing_model')
    op.create_index(op.f('ix_support_tickets_order_id'), 'support_tickets', ['order_id'], unique=False)
    op.create_foreign_key(None, 'support_tickets', 'orders', ['order_id'], ['id'])
    op.add_column('tax_rates', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.add_column('tax_rates', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.alter_column('tax_rates', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('tax_rates', 'priority',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_tax_rates_country_code'), 'tax_rates', ['country_code'], unique=False)
    op.drop_column('tax_rates', 'override')
    op.drop_column('tax_rates', 'active')
    op.drop_column('tax_rates', 'postal_code_pattern')
    op.drop_column('tax_rates', 'country')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tax_rates', sa.Column('country', sa.VARCHAR(length=8), nullable=True))
    op.add_column('tax_rates', sa.Column('postal_code_pattern', sa.VARCHAR(length=128), nullable=True))
    op.add_column('tax_rates', sa.Column('active', sa.BOOLEAN(), nullable=False))
    op.add_column('tax_rates', sa.Column('override', sa.BOOLEAN(), nullable=False))
    op.drop_index(op.f('ix_tax_rates_country_code'), table_name='tax_rates')
    op.alter_column('tax_rates', 'priority',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tax_rates', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('tax_rates', 'is_active')
    op.drop_column('tax_rates', 'country_code')
    op.drop_constraint(None, 'support_tickets', type_='foreignkey')
    op.drop_index(op.f('ix_support_tickets_order_id'), table_name='support_tickets')
    op.add_column('suppliers', sa.Column('billing_model', sa.VARCHAR(length=50), server_default=sa.text("'commission'"), nullable=True))
    op.add_column('suppliers', sa.Column('subscription_plan_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'logo_url')
    op.drop_column('suppliers', 'description')
    op.add_column('stores', sa.Column('return_policy', sa.TEXT(), nullable=True))
    op.add_column('stores', sa.Column('shipping_policy', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_products_name_en'), table_name='products')
    op.drop_index(op.f('ix_products_category_en'), table_name='products')
    op.drop_column('products', 'category_en')
    op.drop_column('products', 'description_en')
    op.drop_column('products', 'name_en')
    op.drop_index(op.f('ix_product_variation_variable_values_identifier'), table_name='product_variation_variable_values')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_affiliate_id'), table_name='orders')
    op.drop_column('orders', 'affiliate_commission')
    op.drop_column('orders', 'affiliate_id')
    op.drop_column('orders', 'shipping_cost')
    op.drop_column('order_items', 'affiliate_commission')
    op.drop_column('fulfillment_orders', 'total_affiliate_commission')
    op.drop_column('fulfillment_orders', 'total_shipping_cost')
    op.drop_column('fulfillment_orders', 'total_vendor_share')
    op.drop_index(op.f('ix_cms_widgets_id'), table_name='cms_widgets')
    op.alter_column('cms_widgets', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_index(op.f('ix_cms_pages_id'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_slug'), table_name='cms_pages')
    op.create_index('ix_cms_pages_slug', 'cms_pages', ['slug'], unique=False)
    op.alter_column('cms_pages', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_column('categories', 'description_en')
    op.drop_column('categories', 'name_en')
    op.create_table('advertisements',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('vendor_id', sa.INTEGER(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('target_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('placement', sa.VARCHAR(length=50), server_default=sa.text("'homepage_hero'"), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('cost', sa.FLOAT(), server_default=sa.text('(0.0)'), nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cms_ads',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('zone', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sqlite.JSON(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('start_at', sa.DATETIME(), nullable=True),
    sa.Column('end_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cms_ads_id', 'cms_ads', ['id'], unique=False)
    op.create_table('ui_widgets',
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('settings_json', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_ui_widgets_id', 'ui_widgets', ['id'], unique=False)
    op.create_table('markup_rules',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=True),
    sa.Column('category_id', sa.INTEGER(), nullable=True),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('is_global', sa.BOOLEAN(), nullable=False),
    sa.Column('markup_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('markup_value', sa.FLOAT(), nullable=False),
    sa.Column('min_price', sa.FLOAT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_markup_rules_supplier_id', 'markup_rules', ['supplier_id'], unique=False)
    op.create_index('ix_markup_rules_product_id', 'markup_rules', ['product_id'], unique=False)
    op.create_index('ix_markup_rules_id', 'markup_rules', ['id'], unique=False)
    op.create_index('ix_markup_rules_category_id', 'markup_rules', ['category_id'], unique=False)
    op.create_table('admin_settings',
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(length=100), nullable=False),
    sa.Column('value', sa.TEXT(), nullable=True),
    sa.Column('data_type', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_settings_key', 'admin_settings', ['key'], unique=False)
    op.create_index('ix_admin_settings_id', 'admin_settings', ['id'], unique=False)
    op.create_table('cms_widgets_legacy',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('content', sqlite.JSON(), nullable=True),
    sa.Column('page', sa.VARCHAR(), nullable=True),
    sa.Column('position', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('device', sa.VARCHAR(), nullable=True),
    sa.Column('start_at', sa.DATETIME(), nullable=True),
    sa.Column('end_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cms_widgets_legacy_id', 'cms_widgets_legacy', ['id'], unique=False)
    op.create_table('cms_theme_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('key', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_cms_theme_settings_id', 'cms_theme_settings', ['id'], unique=False)
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.create_table('vendor_followers',
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('supplier_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vendor_followers_user_id', 'vendor_followers', ['user_id'], unique=False)
    op.create_index('ix_vendor_followers_supplier_id', 'vendor_followers', ['supplier_id'], unique=False)
    op.create_index('ix_vendor_followers_id', 'vendor_followers', ['id'], unique=False)
    # ### end Alembic commands ###
